In [2]:
# to delete a shell press dd
import numpy as np
c= np.array([[1,2,3,4],[11,22,33,44],[5,7,9,90]])

In [3]:
c

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44],
       [ 5,  7,  9, 90]])

In [4]:
c[0,0]

1

In [7]:
c[1,2]

33

In [10]:
# 1:3 means 1 till 3rdcolumn(3rd excluding) will be accessed of 3rd row(on 2nd index)
c[2,1:3]

array([7, 9])

In [11]:
c[1:3,2:4]

array([[33, 44],
       [ 9, 90]])

In [12]:
c[1:,2:]

array([[33, 44],
       [ 9, 90]])

In [13]:
c[0:3,3]

array([ 4, 44, 90])

# arange function

In [14]:
list(range(5,51))

[5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

In [15]:
#advantages:
#not needed to include in list
#floating range can also be given
np.arange(5,51)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

# Reshape function

In [17]:
a=np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
# to make matrix from given range:
a=np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
np.sqrt(4)

2.0

In [22]:
a=np.arange(12).reshape(3,4)
a.max()

11

In [23]:
# position(index) of max or min element
a.argmax()

11

In [24]:
a.argmin()

0

In [25]:
a*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

# Random

In [27]:
np.random.rand(2,2)

array([[0.01195456, 0.45506746],
       [0.86362691, 0.27924591]])

In [28]:
np.random.randn(2,2)

array([[-0.54606217,  0.89096361],
       [ 2.26464407, -0.50508237]])

In [29]:
# random 10 values from 9 to 99
np.random.randint(9,90,10)

array([81, 85, 22, 58, 28, 73, 36, 77, 12, 82])

In [32]:
s=np.random.randint(9,90,12).reshape(6,2)

array([[49, 80],
       [22, 57],
       [12, 56],
       [17, 60],
       [23, 14],
       [25, 26]])

In [35]:
s=np.random.randint(9,90,12).reshape(6,2)
s.sum()

563

In [36]:
#rowwise sum
s.sum(axis=1)

array([ 86, 140, 106,  63,  97,  71])

In [37]:
#columnwise sum
s.sum(axis=0)

array([357, 206])

# 3D 

In [39]:
d=np.array([[[4,40],[5,50],[6,60]],[[7,70],[8,80],[9,90]],[[5,55],[4,40],[6,60]]])
d.shape

(3, 3, 2)

In [40]:
# HW(4, 3, 4)

In [41]:
d

array([[[ 4, 40],
        [ 5, 50],
        [ 6, 60]],

       [[ 7, 70],
        [ 8, 80],
        [ 9, 90]],

       [[ 5, 55],
        [ 4, 40],
        [ 6, 60]]])

In [42]:
# Nan-not a number

In [43]:
x=np.array([12,56,np.nan,66,100,np.nan])

In [44]:
x

array([ 12.,  56.,  nan,  66., 100.,  nan])

In [45]:
x.dtype

dtype('float64')